#!/bin/bash  
memusage=$(free -h | awk '$1 == "Mem:" {print "total:", $2, "free:", $4, "used:", $3}')
echo " the total memoryused is : $memusage " 
diskusage=$(df -h | awk '$6=="/"{ print $5}')
echo " the total disk usage by the system : $diskusage"  


